version: '2'

# Services/containers to run
services:
  usermanager:
    build: .
    ports:
      - "3000:3000"
    links:
      - database
    volumes:
      - .:/opt/app
    depends_on:
      - database

  database:
      image: mongo # specify image to build container from
